version: "3.9"

services:
  consul:
    image: bitnami/consul
    container_name: "consul"
    ports:
      - "8500:8500"
    command: "consul agent -dev -ui -client=0.0.0.0"

  gateway_db:
    image: postgres:16.2
    ports:
      - "5433:5432"
    volumes:
      - ./data/gateway-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=evheniy
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=gateway_db