server:
  port: 1000
  error:
    include-message: always
    include-binding-errors: always

oauth:
  google:
    clientId: ""
    clientSecret: ""
    scope: "openid profile email"

spring:
  application:
    name: gateway
  config:
    import: optional:consul:/
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /health
        health-check-url: http://host.docker.internal:1000/health
    gateway:
      routes:
        - id: gateway-oauth-route
          uri: lb://gateway
          predicates:
            - Path=/oauth/**
        - id: car-management-route
          uri: lb://car-management
          predicates:
            - Path=/api/car/**
          filters:
            - RewritePath=/api/car/(?<remaining>.*), /api/car/${remaining}
        - id: brand-management-route
          uri: lb://car-management
          predicates:
            - Path=/api/brand/**
          filters:
            - RewritePath=/api/brand/(?<remaining>.*), /api/brand/${remaining}
  r2dbc:
      url: r2dbc:postgresql://localhost:5433/gateway_db
      username: evheniy
      password: password123
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  sql:
      init:
        mode: always
        schema-locations: classpath:schema.sql

resilience4j:
  circuitbreaker:
    instances:
      services:
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 60
        slow-call-duration-threshold:
          - 2s
        minimum-number-of-calls: 3
        permitted-number-of-calls-in-half-open-state: 1


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
